version: '2'

services:
  telegraf-client:
    image: registry.lennick.ca/telegraf-client:arm
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW 
    restart: never